# Generated by Django 5.0.1 on 2024-02-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.AutoField(db_column='IdProducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('precio', models.DecimalField(blank=True, db_column='Precio', decimal_places=2, max_digits=10, null=True)),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('stock', models.IntegerField(blank=True, db_column='Stock', null=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoStock',
            fields=[
                ('idproducto', models.ForeignKey(blank=True, db_column='IdProducto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='producto.productos')),
                ('cantidadactual', models.IntegerField(blank=True, db_column='CantidadActual', null=True)),
            ],
            options={
                'db_table': 'producto_stock',
            },
        ),
    ]
