# Generated by Django 5.0.1 on 2024-01-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('idempleado', models.AutoField(db_column='IdEmpleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=255, null=True)),
                ('contrasena', models.CharField(db_column='Contrasena', max_length=20)),
                ('edad', models.IntegerField(blank=True, db_column='Edad', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Empleados',
            },
        ),
    ]
