# Generated by Django 5.0.1 on 2024-01-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='contrasena',
            field=models.CharField(db_column='Contrasena', max_length=255),
        ),
    ]
