# Generated by Django 5.0.1 on 2024-01-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_empleados_contrasena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=255, null=True, unique=True),
        ),
    ]
