# Generated by Django 5.0.1 on 2024-01-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_empleados_groups_empleados_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='contrasena',
            field=models.CharField(db_column='Contrasena', max_length=255, verbose_name='password'),
        ),
    ]
