# Generated by Django 5.0.1 on 2024-01-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_empleados_contrasena'),
    ]

    operations = [
    ]
