# Generated by Django 5.0.1 on 2024-01-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_empleados_contrasena_alter_empleados_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='password',
            field=models.CharField(db_column='password', max_length=255),
        ),
    ]
