# Generated by Django 5.0.1 on 2024-01-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_remove_empleados_contrasena_alter_empleados_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='direccion',
            field=models.CharField(blank=True, db_column='Direccion', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleados',
            name='sexo',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], default='Hombre', max_length=6),
        ),
    ]
