# Generated by Django 5.0.1 on 2024-02-10 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(db_column='IdCliente', primary_key=True, serialize=False)),
                ('apellidos', models.CharField(blank=True, db_column='Apellidos', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, db_column='Direccion', null=True)),
                ('metodo_de_pago', models.CharField(blank=True, db_column='Metodo_de_pago', max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
