# Generated by Django 5.0.1 on 2024-02-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='apellidos',
            field=models.CharField(blank=True, db_column='Apellidos', max_length=255, null=True),
        ),
    ]
