# Generated by Django 5.0.1 on 2024-02-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturasCabecera',
            fields=[
                ('idfactura', models.AutoField(db_column='IdFactura', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('pago', models.DecimalField(blank=True, db_column='Pago', decimal_places=2, max_digits=10, null=True)),
                ('direccion', models.TextField(blank=True, db_column='Direccion', null=True)),
                ('preciototal', models.DecimalField(blank=True, db_column='PrecioTotal', decimal_places=2, max_digits=10, null=True)),
                ('idcliente', models.ForeignKey(blank=True, db_column='IdCliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.clientes')),
            ],
            options={
                'db_table': 'facturas_cabecera',
            },
        ),
        migrations.CreateModel(
            name='FacturasCompuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('precio', models.DecimalField(blank=True, db_column='Precio', decimal_places=2, max_digits=10, null=True)),
                ('idfactura', models.ForeignKey(blank=True, db_column='IdFactura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='facturas.facturascabecera')),
                ('idproducto', models.ForeignKey(blank=True, db_column='IdProducto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='producto.productos')),
            ],
            options={
                'db_table': 'facturas_compuesto',
            },
        ),
    ]
