# Generated by Django 5.0.1 on 2024-02-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facturascompuesto',
            constraint=models.UniqueConstraint(fields=('idfactura', 'idproducto'), name='facturas_compuesto_idfactura_idproducto_key'),
        ),
    ]
