# Generated by Django 5.0.1 on 2024-02-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('idproveedor', models.AutoField(db_column='IdProveedor', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, db_column='Direccion', null=True)),
            ],
            options={
                'db_table': 'proveedores',
            },
        ),
    ]
